<?php

namespace P4Louvre\TicketsBundle\Repository;
use DateTime;
use Doctrine\ORM\EntityRepository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends EntityRepository
{
    public function getBookingsUnpaidBefore(DateTime $date)
    {
        return $this->createQueryBuilder('b')
            ->where('b.commandDate <= :date')
            ->andWhere('b.paid = false')
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult()
            ;
    }
}
