<?php

namespace P4Louvre\TicketsBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNbTicketsByDate($date)
    {
        $qb = $this->createQueryBuilder('b');
        $qb
            ->select('COUNT(b.totalNbTickets)')
            ->where('b.ticketDate = :date')
            ->andWhere('b.paid = true')
            ->setParameter('date', $date)
        ;
        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
