<?php

namespace P4Louvre\TicketsBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * VisitorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitorsRepository extends EntityRepository
{
    public function findNbTicketsByDate($date)
    {
        return $this->createQueryBuilder('v')
            ->leftJoin('v.booking', 'b')
            ->addSelect('b.id')
            ->where('v.ticketDate = :date')
            ->andWhere('b.paid = true')
            ->setParameter('date', $date)
            ->getQuery()
            ->getResult();

    }
}
